### ISSUE TITLE
Wire.begin() should not be used within a library

### ISSUE THREAD

**Issue by coelner** [sparkfun/SparkFun_CCS811_Arduino_Library#13]
https://github.com/sparkfun/SparkFun_CCS811_Arduino_Library/blob/0a7c7fe00060601ba23af3555b9c8a59ddd7de12/src/SparkFunCCS811.cpp#L51

The `Wire.begin()` call is bad because it resets the bus. It should only be called by the upper instance. If the user defined other pins for I2C these pins get lost.

See here: https://github.com/esp8266/Arduino/issues/2607

**Comment by nseidle** [comment]
Agreed. And the whole thing should be re-written to not hard-code the wire port.

**Comment by nseidle** [comment]
Fixed in v1.0.5.
