### ISSUE TITLE
Wire library buffer does not need to be cleared

### ISSUE THREAD

**Issue by Koepel** [sparkfun/SparkFun_CCS811_Arduino_Library#4]
The Wire library buffer is cleared in "SparkFunCCS811.cpp". That is not needed at all.

The beginCore() clears the Wire buffer as a precaution. That is not needed.

In multiReadRegister() is a 'dump extra' to clear the Wire buffer. That is not needed.
Explanation: [Common-mistakes#4](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#4)

The delay in begin() should be reconsidered. Incrementing a volatile variable might work for now (or not) but there is no guarantee that it will work in the future.

**Comment by nseidle** [comment]
Removed lines 71 - Wire buffer clear.

Removed lines 160 - extra wire reading/dump

I agree with you, hard coded delays in general make me nervous but we have been chasing timing issues with this sensor and the ESP architecture. I'm leaving them for now.
