### ISSUE TITLE
Error compiling Arduino 1.8.5

### ISSUE THREAD

**Issue by markuspmeyer** [sparkfun/SparkFun_CCS811_Arduino_Library#7]
Arduino 1.8.5

[SparkFunCCS811.cpp.patch.gz](https://github.com/sparkfun/SparkFun_CCS811_Arduino_Library/files/1609903/SparkFunCCS811.cpp.patch.gz)

**Comment by nseidle** [comment]
For my own documentation:

 	//Return value
-	uint8_t result;
+	uint8_t result = 1;
 	uint8_t numBytes = 1;
 	CCS811Core::status returnError = SENSOR_SUCCESS;
 	Wire.beginTransmission(I2CAddress);

**Comment by nseidle** [comment]
Incorporated in latest version. Thanks!
